### PR TITLE
feat(yt-dl): automatically gather youtube cookies

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Description

This PR adds the ability to automatically consent and collect cookies from YouTube.com.

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I want maintainers to keep my branch updated

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
We might be able to use selenium manager to handle driver updates. https://www.selenium.dev/documentation/selenium_manager/

**Comment by ReenigneArcher** [comment]
I think selenium is being imported from Plex's framework instead of from the version we installed. We can possibly adjust the path order.

**Comment by ReenigneArcher** [comment]
@zdimension do you think this feature is worth continuing?

**Comment by zdimension** [comment]
> @zdimension do you think this feature is worth continuing?

Honestly, I think it will only get more difficult in the future to log in to YT in an automated fashion, like we're doing here, so I'm not sure it's worth the hassle. I mean, I've put my YT cookies in the Themerr settings a month or two ago and since then it's been working flawlessly (except for region locked content, but we're not getting past that anyway unless we use a proxy or VPN). So manually filling in the cookies doesn't seem to be that much of a problem, to me.

**Comment by ReenigneArcher** [comment]
Alright, there were other cleanups in here. I'll pull those out into a separate PR.

And I think there's an option in youtube-dl to use a proxy. That should probably be added as a config option for both youtube-dl and accessing ThemerrDB/GitHub.

**Pull request closed without merging**
